version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # enviornment-file:
    #   - ./.env
    
# PRODUCTION: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build
# DEVELOPMENT: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
